security:
    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

    encoders:
#        Symfony\Component\Security\Core\User\User: sha512
        YangBo\Bundle\DreamBlogBundle\Entity\User: sha512

