security:
    providers:
        chain_provider:
            chain:
                providers: [in_memory, user_db]
        in_memory:
            memory:
                users:
                    yangbo:
                        password: yangbo
                        roles: 'ROLE_USER'
                    admins:
#                        password: adminadmin
                        password: $2a$12$wNeWwCP7eBSojIf/NoOLl.s.hlao5alyliRhdj4gEQyqIVAl.wD4y
                        roles: 'ROLE_ADMIN'
        user_db:
            entity: { class: YangBo\Bundle\DreamBlogBundle\Entity\User, property:username }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false


        default:
            anonymous: ~
            http_basic: ~
            form_login:
                login_path: /admin/login
                check_path: /admin/login_check
            remember_me:
                            key: "%secret%"
                            name: yang_bo_dream_blog_admin_remember  #cookie name
                            lifetime: 604800
                            path: /
            logout:
                path: /admin/logout
                target: /


    access_control:
        - { path: ^/admin/login|^/admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login_check, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: [ROLE_ADMIN]}


    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext
#        YangBo\Bundle\DreamBlogBundle\Entity\User: sha512

        YangBo\Bundle\DreamBlogBundle\Entity\User:
            algorithm: bcrypt
            cost: 12


        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

