YangBo\Bundle\DreamBlogBundle\Entity\Category:
    type: entity
    table: category
    repositoryClass: YangBo\Bundle\DreamBlogBundle\Entity\CategoryRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 200
#        pid:
#            type: integer
        updated_at:
            type: datetime
            nullable: true
        created_at:
            type: datetime
#    manyToMany:
#        articles:
#            targetEntity: Article
#            inversedBy: categories
#            joinTable:
#                name: category_article
#                JoinColumns:
#                    category_id:
#                        referencedColumnName: id
#                inverseJoinColumns:
#                    article_id:
#                        referencedColumnName: id

    manyToMany:
        articles:
            targetEntity: Article
            mappedBy: categories
    oneToMany:
        children:
            targetEntity: Category
            mappedBy: parent
    manyToOne:
        parent:
            targetEntity: Category
            inversedBy: childen
#            joinColumns:
#                pid:
#                    referencedColumnName: id
    lifecycleCallbacks:
        prePersist: [ setCreatedAtOnPrePersist ]