<?php

namespace YangBo\Bundle\DreamBlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    // 推荐文章
    public function getRecommendArticles($count = null)
    {
        //推荐 文章
        $dql_sql = 'SELECT article,u FROM YangBoDreamBlogBundle:Article article LEFT JOIN article.user u WHERE article.is_recommend = :recommend ';
        $recommend_articles = $this->getEntityManager($dql_sql)
//            ->createQuery('SELECT article FROM YangBo\Bundle\DreamBlogBundle\Entity\Article article WHERE article.is_recommend = :recommend')
//            ->createQuery('SELECT article FROM YangBoDreamBlogBundle:Article article WHERE article.is_recommend = :recommend ')
            ->createQuery($dql_sql)
            ->setParameter('recommend', true)
            ->setMaxResults($count)
            ->getResult();
        return $recommend_articles;
    }

    //最新文章
    public function getNewestArticles($count = null)
    {
        $dql_sql = 'SELECT article FROM YangBoDreamBlogBundle:Article article ORDER BY article.created_at DESC, article.page_view_count DESC';
        // 最新 文章
        $newest_articles = $this
            ->getEntityManager()
            ->createQuery($dql_sql)
            ->setMaxResults($count)
            ->getResult();
        return $newest_articles;
    }

    public function getMostViewArticles($count = null)
    {
        $most_view_articles = $this
            ->getEntityManager()
            ->createQuery('SELECT article FROM YangBoDreamBlogBundle:Article article ORDER BY article.page_view_count DESC')
            ->setMaxResults($count)
            ->getResult();
        return $most_view_articles;
    }


}
