services:
#    yang_bo_dream_blog.example:
#        class: YangBo\Bundle\DreamBlogBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    app.twig_extension:
        class: Twig_Extensions_Extension_Date
        public: false
#        arguments: [@translator]
        tags:
            - { name: twig.extension }